### ISSUE TITLE
Add a Readme

### ISSUE THREAD

**Issue by 8G6** [8G6/Code-A-Tune#1]
help me to add a good readme to this project

**Comment by aanchal-fatwani** [comment]
Hi @8G6 , I'd like to work on this issue. I have a structure in mind to create a good Readme(with sub-sections, and links - for ease of reading, setup steps, tech, features, scope, etc)
Please assign me this issue to allow me to proceed with the same. 
Thanks.

**Comment by 8G6** [comment]
Done, If you need any help in docs please feel free to ask

**Comment by 8G6** [comment]
@aanchal-fatwani  great work thank you
